apiVersion: v1
kind: Namespace
metadata:
  name: getit-development
  labels:
    name: getit-development
    environment: development
    platform: getit-bangladesh
    tier: application
  annotations:
    description: "GetIt Bangladesh Multi-Vendor E-commerce Development Environment"
    contact: "development-team@getit.com.bd"
    cost-center: "development"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: development-resource-quota
  namespace: getit-development
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 20Gi
    limits.cpu: "20"
    limits.memory: 40Gi
    persistentvolumeclaims: "20"
    pods: "50"
    services: "20"
    secrets: "30"
    configmaps: "30"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: development-limit-range
  namespace: getit-development
spec:
  limits:
  - default:
      cpu: 500m
      memory: 1Gi
    defaultRequest:
      cpu: 100m
      memory: 256Mi
    type: Container
  - max:
      cpu: 2
      memory: 4Gi
    min:
      cpu: 50m
      memory: 128Mi
    type: Container