# Backend ConfigMap for GetIt Bangladesh Multi-Vendor E-commerce Platform
# Amazon.com/Shopee.sg-Level Backend Configuration

apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  labels:
    app: backend
    tier: backend
    project: getit-bangladesh
    config-type: application
data:
  # Server Configuration
  node-env: "production"
  port: "3000"
  workers: "4"
  log-level: "info"
  
  # Database Configuration
  db-pool-min: "5"
  db-pool-max: "20"
  db-connection-timeout: "30000"
  db-idle-timeout: "300000"
  
  # Redis Configuration
  redis-pool-min: "5"
  redis-pool-max: "20"
  redis-ttl: "3600"
  
  # AWS Configuration
  aws-region: "ap-southeast-1"
  s3-bucket: "getit-bangladesh-assets"
  cloudfront-domain: "cdn.getit.com.bd"
  
  # Performance Settings
  enable-clustering: "true"
  enable-compression: "true"
  enable-caching: "true"
  cache-ttl: "300"
  rate-limit-window: "900000"
  rate-limit-max: "1000"
  
  # Security Settings
  enable-helmet: "true"
  enable-cors: "true"
  enable-csrf: "true"
  session-timeout: "3600000"
  jwt-expiry: "3600"
  refresh-token-expiry: "2592000"
  
  # Feature Flags
  enable-websockets: "true"
  enable-graphql: "true"
  enable-api-versioning: "true"
  enable-swagger-docs: "false"
  enable-admin-panel: "true"
  enable-vendor-portal: "true"
  
  # Bangladesh Specific Settings
  default-currency: "BDT"
  supported-currencies: "BDT,USD"
  default-language: "en"
  supported-languages: "en,bn"
  timezone: "Asia/Dhaka"
  country-code: "BD"
  
  # Payment Gateway Settings
  enable-stripe: "true"
  enable-bkash: "true"
  enable-nagad: "true"
  enable-rocket: "true"
  enable-ssl-commerz: "true"
  payment-timeout: "600000"
  
  # Shipping Configuration
  enable-pathao: "true"
  enable-paperfly: "true"
  enable-sundarban: "true"
  enable-redx: "true"
  shipping-calculation-cache: "3600"
  
  # Notification Settings
  enable-email: "true"
  enable-sms: "true"
  enable-push: "true"
  enable-whatsapp: "false"
  notification-retry-attempts: "3"
  notification-retry-delay: "30000"
  
  # Search and Analytics
  elasticsearch-index: "getit-products"
  enable-search-analytics: "true"
  enable-product-recommendations: "true"
  analytics-batch-size: "100"
  
  # File Upload Settings
  max-file-size: "52428800"
  allowed-file-types: "jpg,jpeg,png,gif,webp,pdf,doc,docx"
  upload-path: "/uploads"
  
  # API Rate Limiting
  api-rate-limit: "1000"
  api-rate-window: "900000"
  auth-rate-limit: "5"
  auth-rate-window: "900000"
  
  # Monitoring and Health
  health-check-timeout: "5000"
  metrics-collection-interval: "60000"
  enable-distributed-tracing: "true"
  enable-apm: "true"
  
  # Social Commerce Settings
  enable-social-login: "true"
  enable-social-sharing: "true"
  enable-group-buying: "true"
  enable-live-streaming: "true"
  enable-influencer-program: "true"
  
  # AI and ML Settings
  enable-recommendation-engine: "true"
  enable-fraud-detection: "true"
  enable-sentiment-analysis: "true"
  enable-chatbot: "true"
  ml-model-cache-ttl: "86400"
---
# Database Configuration ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
  labels:
    app: database
    tier: data
    project: getit-bangladesh
    config-type: database
data:
  # PostgreSQL Configuration
  postgres-max-connections: "200"
  postgres-shared-buffers: "256MB"
  postgres-effective-cache-size: "1GB"
  postgres-work-mem: "4MB"
  postgres-maintenance-work-mem: "64MB"
  postgres-random-page-cost: "1.1"
  postgres-temp-file-limit: "2GB"
  postgres-log-min-duration: "1000"
  postgres-log-statement: "all"
  postgres-log-destination: "stderr"
  postgres-logging-collector: "on"
  postgres-log-rotation-age: "1d"
  postgres-log-rotation-size: "1GB"
  
  # Backup Configuration
  backup-retention-days: "30"
  backup-schedule: "0 2 * * *"
  backup-compression: "true"
  backup-encryption: "true"
  
  # Monitoring Configuration
  enable-pg-stat-statements: "true"
  enable-auto-explain: "true"
  auto-explain-log-min-duration: "1s"
  
  # Replication Configuration
  enable-replication: "true"
  max-wal-senders: "3"
  wal-level: "replica"
  archive-mode: "on"
  archive-command: "cp %p /backup/archive/%f"