# Prometheus Configuration for GetIt Bangladesh Multi-Vendor E-commerce Platform
# Amazon.com/Shopee.sg-Level Monitoring and Alerting

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'getit-bangladesh-production'
    region: 'ap-southeast-1'
    environment: 'production'

rule_files:
  - "/etc/prometheus/rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # =============================================================================
  # KUBERNETES MONITORING
  # =============================================================================
  
  # Kubernetes API Server
  - job_name: 'kubernetes-apiservers'
    kubernetes_sd_configs:
    - role: endpoints
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
    - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
      action: keep
      regex: default;kubernetes;https

  # Kubernetes Nodes
  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
    - role: node
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)
    - target_label: __address__
      replacement: kubernetes.default.svc:443
    - source_labels: [__meta_kubernetes_node_name]
      regex: (.+)
      target_label: __metrics_path__
      replacement: /api/v1/nodes/${1}/proxy/metrics

  # Kubernetes Pods
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
    - role: pod
    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
      action: keep
      regex: true
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
      action: replace
      target_label: __metrics_path__
      regex: (.+)
    - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
      action: replace
      regex: ([^:]+)(?::\d+)?;(\d+)
      replacement: $1:$2
      target_label: __address__
    - action: labelmap
      regex: __meta_kubernetes_pod_label_(.+)
    - source_labels: [__meta_kubernetes_namespace]
      action: replace
      target_label: kubernetes_namespace
    - source_labels: [__meta_kubernetes_pod_name]
      action: replace
      target_label: kubernetes_pod_name

  # =============================================================================
  # APPLICATION MONITORING
  # =============================================================================

  # Frontend Services
  - job_name: 'frontend'
    static_configs:
    - targets: ['frontend-service:80']
    metrics_path: /metrics
    scrape_interval: 30s
    relabel_configs:
    - source_labels: [__address__]
      target_label: service
      replacement: frontend
    - source_labels: [__address__]
      target_label: tier
      replacement: frontend

  # Backend Services
  - job_name: 'backend'
    static_configs:
    - targets: ['backend-service:3000']
    metrics_path: /metrics
    scrape_interval: 15s
    relabel_configs:
    - source_labels: [__address__]
      target_label: service
      replacement: backend
    - source_labels: [__address__]
      target_label: tier
      replacement: backend

  # Database Monitoring
  - job_name: 'postgres'
    static_configs:
    - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    relabel_configs:
    - source_labels: [__address__]
      target_label: service
      replacement: postgres
    - source_labels: [__address__]
      target_label: tier
      replacement: database

  # Redis Monitoring
  - job_name: 'redis'
    static_configs:
    - targets: ['redis-exporter:9121']
    scrape_interval: 30s
    relabel_configs:
    - source_labels: [__address__]
      target_label: service
      replacement: redis
    - source_labels: [__address__]
      target_label: tier
      replacement: cache

  # =============================================================================
  # INFRASTRUCTURE MONITORING
  # =============================================================================

  # Node Exporter
  - job_name: 'node-exporter'
    kubernetes_sd_configs:
    - role: endpoints
    relabel_configs:
    - source_labels: [__meta_kubernetes_endpoints_name]
      regex: 'node-exporter'
      action: keep

  # cAdvisor
  - job_name: 'cadvisor'
    kubernetes_sd_configs:
    - role: node
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)
    - target_label: __address__
      replacement: kubernetes.default.svc:443
    - source_labels: [__meta_kubernetes_node_name]
      regex: (.+)
      target_label: __metrics_path__
      replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor

  # =============================================================================
  # BUSINESS METRICS MONITORING
  # =============================================================================

  # E-commerce Business Metrics
  - job_name: 'business-metrics'
    static_configs:
    - targets: ['backend-service:3000']
    metrics_path: /api/v1/metrics/business
    scrape_interval: 60s
    relabel_configs:
    - source_labels: [__address__]
      target_label: service
      replacement: business-metrics
    - source_labels: [__address__]
      target_label: type
      replacement: ecommerce

  # Payment Gateway Metrics
  - job_name: 'payment-metrics'
    static_configs:
    - targets: ['backend-service:3000']
    metrics_path: /api/v1/metrics/payments
    scrape_interval: 30s
    relabel_configs:
    - source_labels: [__address__]
      target_label: service
      replacement: payment-metrics
    - source_labels: [__address__]
      target_label: type
      replacement: financial

  # Order Processing Metrics
  - job_name: 'order-metrics'
    static_configs:
    - targets: ['backend-service:3000']
    metrics_path: /api/v1/metrics/orders
    scrape_interval: 30s
    relabel_configs:
    - source_labels: [__address__]
      target_label: service
      replacement: order-metrics
    - source_labels: [__address__]
      target_label: type
      replacement: operational

  # =============================================================================
  # EXTERNAL SERVICES MONITORING
  # =============================================================================

  # Elasticsearch
  - job_name: 'elasticsearch'
    static_configs:
    - targets: ['elasticsearch:9200']
    metrics_path: /_prometheus/metrics
    scrape_interval: 30s

  # Nginx Ingress Controller
  - job_name: 'nginx-ingress'
    kubernetes_sd_configs:
    - role: pod
      namespaces:
        names:
        - ingress-nginx
    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
      action: keep
      regex: ingress-nginx

  # =============================================================================
  # BLACKBOX MONITORING
  # =============================================================================

  # Website Health Checks
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
    - targets:
      - https://getit.com.bd
      - https://www.getit.com.bd
      - https://api.getit.com.bd/health
      - https://admin.getit.com.bd
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: blackbox-exporter:9115

  # SSL Certificate Monitoring
  - job_name: 'blackbox-ssl'
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
    - targets:
      - getit.com.bd:443
      - api.getit.com.bd:443
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: blackbox-exporter:9115

# Storage configuration
storage:
  tsdb:
    path: /prometheus/data
    retention.time: 30d
    retention.size: 100GB
    wal-compression: true