apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: getit-production
  labels:
    app: elasticsearch
    component: search-database
    platform: getit-bangladesh
    tier: infrastructure
  annotations:
    description: "Elasticsearch Cluster for Search and Logging - GetIt Bangladesh"
    contact: "database-team@getit.com.bd"
spec:
  serviceName: elasticsearch-headless
  replicas: 3
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
        component: search-database
        platform: getit-bangladesh
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsNonRoot: true
      initContainers:
      - name: elasticsearch-init
        image: busybox:1.36
        command:
        - /bin/sh
        - -c
        - |
          # Increase vm.max_map_count
          sysctl -w vm.max_map_count=262144
          # Set proper permissions
          chown -R 1000:1000 /usr/share/elasticsearch/data
        securityContext:
          privileged: true
        volumeMounts:
        - name: elasticsearch-data
          mountPath: /usr/share/elasticsearch/data
      containers:
      - name: elasticsearch
        image: elasticsearch:8.11.3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        env:
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: cluster.name
          value: getit-elasticsearch
        - name: discovery.seed_hosts
          value: "elasticsearch-0.elasticsearch-headless.getit-production.svc.cluster.local,elasticsearch-1.elasticsearch-headless.getit-production.svc.cluster.local,elasticsearch-2.elasticsearch-headless.getit-production.svc.cluster.local"
        - name: cluster.initial_master_nodes
          value: "elasticsearch-0,elasticsearch-1,elasticsearch-2"
        - name: node.data
          value: "true"
        - name: node.master
          value: "true"
        - name: node.ingest
          value: "true"
        - name: network.host
          value: "0.0.0.0"
        - name: ES_JAVA_OPTS
          value: "-Xms4g -Xmx4g"
        - name: xpack.security.enabled
          value: "true"
        - name: xpack.security.transport.ssl.enabled
          value: "false"
        - name: xpack.security.http.ssl.enabled
          value: "false"
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: elasticsearch-password
        - name: xpack.monitoring.collection.enabled
          value: "true"
        - name: bootstrap.memory_lock
          value: "false"
        - name: action.destructive_requires_name
          value: "true"
        - name: cluster.routing.allocation.disk.threshold_enabled
          value: "true"
        - name: cluster.routing.allocation.disk.watermark.low
          value: "85%"
        - name: cluster.routing.allocation.disk.watermark.high
          value: "90%"
        - name: cluster.routing.allocation.disk.watermark.flood_stage
          value: "95%"
        - name: indices.memory.index_buffer_size
          value: "10%"
        - name: indices.fielddata.cache.size
          value: "20%"
        - name: indices.queries.cache.size
          value: "10%"
        volumeMounts:
        - name: elasticsearch-data
          mountPath: /usr/share/elasticsearch/data
        - name: elasticsearch-config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
        - name: elasticsearch-jvm-config
          mountPath: /usr/share/elasticsearch/config/jvm.options
          subPath: jvm.options
        resources:
          requests:
            memory: "8Gi"
            cpu: "2"
          limits:
            memory: "16Gi"
            cpu: "4"
        livenessProbe:
          httpGet:
            path: /_cluster/health
            port: 9200
            httpHeaders:
            - name: Authorization
              value: "Basic ZWxhc3RpYzpjaGFuZ2VtZQ=="
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /_cluster/health
            port: 9200
            httpHeaders:
            - name: Authorization
              value: "Basic ZWxhc3RpYzpjaGFuZ2VtZQ=="
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /_cluster/health
            port: 9200
            httpHeaders:
            - name: Authorization
              value: "Basic ZWxhc3RpYzpjaGFuZ2VtZQ=="
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 60
      volumes:
      - name: elasticsearch-config
        configMap:
          name: elasticsearch-config
      - name: elasticsearch-jvm-config
        configMap:
          name: elasticsearch-jvm-config
  volumeClaimTemplates:
  - metadata:
      name: elasticsearch-data
      labels:
        app: elasticsearch
        component: search-database
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: logs-storage
      resources:
        requests:
          storage: 1Ti
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: getit-production
  labels:
    app: elasticsearch
    component: search-database
    platform: getit-bangladesh
  annotations:
    description: "Elasticsearch Service for GetIt Bangladesh"
spec:
  type: ClusterIP
  ports:
  - port: 9200
    targetPort: 9200
    protocol: TCP
    name: http
  - port: 9300
    targetPort: 9300
    protocol: TCP
    name: transport
  selector:
    app: elasticsearch
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-headless
  namespace: getit-production
  labels:
    app: elasticsearch
    component: search-database
    platform: getit-bangladesh
  annotations:
    description: "Elasticsearch Headless Service for StatefulSet"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 9200
    targetPort: 9200
    protocol: TCP
    name: http
  - port: 9300
    targetPort: 9300
    protocol: TCP
    name: transport
  selector:
    app: elasticsearch
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: getit-production
  labels:
    app: elasticsearch
    component: search-database
    platform: getit-bangladesh
data:
  elasticsearch.yml: |
    # Elasticsearch Configuration for GetIt Bangladesh Production
    
    # Cluster
    cluster.name: getit-elasticsearch
    node.name: ${node.name}
    
    # Network
    network.host: 0.0.0.0
    http.port: 9200
    transport.port: 9300
    
    # Discovery
    discovery.seed_hosts: 
      - "elasticsearch-0.elasticsearch-headless.getit-production.svc.cluster.local"
      - "elasticsearch-1.elasticsearch-headless.getit-production.svc.cluster.local"
      - "elasticsearch-2.elasticsearch-headless.getit-production.svc.cluster.local"
    cluster.initial_master_nodes:
      - "elasticsearch-0"
      - "elasticsearch-1" 
      - "elasticsearch-2"
    
    # Node Roles
    node.roles: [ master, data, ingest, ml, remote_cluster_client, transform ]
    
    # Path
    path.data: /usr/share/elasticsearch/data
    path.logs: /usr/share/elasticsearch/logs
    
    # Memory
    bootstrap.memory_lock: false
    
    # Security
    xpack.security.enabled: true
    xpack.security.enrollment.enabled: false
    xpack.security.http.ssl.enabled: false
    xpack.security.transport.ssl.enabled: false
    
    # Monitoring
    xpack.monitoring.collection.enabled: true
    
    # Index Management
    action.destructive_requires_name: true
    
    # Cluster Settings
    cluster.routing.allocation.disk.threshold_enabled: true
    cluster.routing.allocation.disk.watermark.low: 85%
    cluster.routing.allocation.disk.watermark.high: 90%
    cluster.routing.allocation.disk.watermark.flood_stage: 95%
    cluster.routing.allocation.node_concurrent_recoveries: 2
    cluster.routing.allocation.cluster_concurrent_rebalance: 2
    
    # Indices Settings
    indices.memory.index_buffer_size: 10%
    indices.fielddata.cache.size: 20%
    indices.queries.cache.size: 10%
    indices.requests.cache.size: 1%
    
    # Thread Pool
    thread_pool.write.queue_size: 1000
    thread_pool.search.queue_size: 1000
    thread_pool.get.queue_size: 1000
    
    # Search Settings
    search.max_buckets: 65536
    search.max_open_scroll_context: 500
    
    # Bangladesh Specific Settings
    cluster.info.update.interval: 30s
    
    # Logging
    logger.org.elasticsearch.discovery: DEBUG
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-jvm-config
  namespace: getit-production
  labels:
    app: elasticsearch
    component: search-database
    platform: getit-bangladesh
data:
  jvm.options: |
    # JVM Configuration for Elasticsearch
    
    # Heap Size (50% of container memory)
    -Xms4g
    -Xmx4g
    
    # GC Configuration
    -XX:+UseG1GC
    -XX:G1HeapRegionSize=32m
    -XX:+UseG1MixedGCCountTarget=8
    -XX:+UseG1NewSizePercent=30
    -XX:+UseG1MaxNewSizePercent=40
    -XX:+UseG1OldGCPercent=10
    -XX:G1MixedGCLiveThresholdPercent=85
    
    # Memory Management
    -XX:+AlwaysPreTouch
    -Xss1m
    -XX:+UseCompressedOops
    -XX:+UseCompressedClassPointers
    
    # Performance
    -XX:+OptimizeStringConcat
    -XX:+UseStringDeduplication
    -XX:+UnlockExperimentalVMOptions
    -XX:+UseCGroupMemoryLimitForHeap
    
    # Debugging (disabled in production)
    # -XX:+PrintGCDetails
    # -XX:+PrintGCTimeStamps
    # -XX:+PrintGCApplicationStoppedTime
    
    # Fatal Error Logs
    -XX:+ExitOnOutOfMemoryError
    -XX:+CrashOnOutOfMemoryError
    
    # File Encoding
    -Dfile.encoding=UTF-8
    
    # Temporary Directory
    -Djava.io.tmpdir=${ES_TMPDIR}
    
    # HeapDump on OOM
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:HeapDumpPath=/usr/share/elasticsearch/data
    
    # JVM Bug Workarounds
    -XX:+UnlockDiagnosticVMOptions
    -XX:+DebugNonSafepoints
    
    # Security Manager
    -Djava.security.policy=all.policy
    
    # Bangladesh Timezone
    -Duser.timezone=Asia/Dhaka