apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: getit-production
  labels:
    app: order-service
    component: core-service
    platform: getit-bangladesh
    tier: backend
    domain: transaction
  annotations:
    description: "Order Management Service for GetIt Bangladesh"
    contact: "backend-team@getit.com.bd"
    deployment.kubernetes.io/revision: "1"
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 3
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
        component: core-service
        platform: getit-bangladesh
        version: v2.0.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: order-service
        image: getit-bangladesh/order-service:2.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3003
          name: http
          protocol: TCP
        - containerPort: 9090
          name: metrics
          protocol: TCP
        env:
        # Database Configuration
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: postgresql-url
        - name: DATABASE_READ_URL
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: postgresql-read-replica-url
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: mongodb-url
        
        # Redis Configuration
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: cache-secrets
              key: redis-url
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cache-secrets
              key: redis-password
        
        # Service Configuration
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3003"
        - name: SERVICE_NAME
          value: "order-service"
        - name: SERVICE_VERSION
          value: "2.0.0"
        
        # Performance Configuration
        - name: MAX_CONNECTIONS
          value: "300"
        - name: POOL_SIZE
          value: "30"
        - name: CACHE_TTL
          value: "1800"
        - name: ORDER_CACHE_TTL
          value: "900"
        
        # Feature Flags
        - name: ENABLE_ORDER_SPLITTING
          value: "true"
        - name: ENABLE_REAL_TIME_TRACKING
          value: "true"
        - name: ENABLE_AUTO_CANCELLATION
          value: "true"
        - name: ENABLE_PAYMENT_RETRY
          value: "true"
        - name: ENABLE_INVENTORY_RESERVATION
          value: "true"
        
        # Bangladesh Configuration
        - name: DEFAULT_CURRENCY
          value: "BDT"
        - name: DEFAULT_TIMEZONE
          value: "Asia/Dhaka"
        - name: SUPPORTED_LANGUAGES
          value: "bn,en,hi,ar"
        - name: VAT_RATE
          value: "15"
        - name: COD_ENABLED
          value: "true"
        
        # Bangladesh Payment Methods
        - name: BKASH_ENABLED
          value: "true"
        - name: NAGAD_ENABLED
          value: "true"
        - name: ROCKET_ENABLED
          value: "true"
        - name: BANK_TRANSFER_ENABLED
          value: "true"
        
        # External Service URLs
        - name: USER_SERVICE_URL
          value: "http://user-service:3000"
        - name: PRODUCT_SERVICE_URL
          value: "http://product-service:3002"
        - name: PAYMENT_SERVICE_URL
          value: "http://payment-service:3004"
        - name: INVENTORY_SERVICE_URL
          value: "http://inventory-service:3005"
        - name: SHIPPING_SERVICE_URL
          value: "http://shipping-service:3006"
        - name: VENDOR_SERVICE_URL
          value: "http://vendor-service:3001"
        - name: NOTIFICATION_SERVICE_URL
          value: "http://notification-service:3007"
        - name: ANALYTICS_SERVICE_URL
          value: "http://analytics-service:3009"
        
        # Order Processing Configuration
        - name: MAX_ORDER_ITEMS
          value: "50"
        - name: ORDER_TIMEOUT_MINUTES
          value: "30"
        - name: PAYMENT_TIMEOUT_MINUTES
          value: "15"
        - name: AUTO_CANCEL_HOURS
          value: "24"
        - name: MAX_CART_ITEMS
          value: "100"
        
        # Business Rules
        - name: MIN_ORDER_VALUE_BDT
          value: "100"
        - name: FREE_SHIPPING_THRESHOLD_BDT
          value: "1000"
        - name: COD_MAX_AMOUNT_BDT
          value: "50000"
        - name: EXPRESS_DELIVERY_CUTOFF_HOUR
          value: "14"
        
        # Security Configuration
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: jwt-secret
        - name: API_KEY_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: api-key-secret
        - name: WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: webhook-secret
        
        volumeMounts:
        - name: order-documents
          mountPath: /app/uploads/orders
        - name: temp-storage
          mountPath: /tmp
        - name: logs
          mountPath: /app/logs
        
        resources:
          requests:
            memory: "1.5Gi"
            cpu: "750m"
          limits:
            memory: "6Gi"
            cpu: "3"
        
        livenessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /ready
            port: 3003
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        
        startupProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 30
      
      volumes:
      - name: order-documents
        persistentVolumeClaim:
          claimName: order-documents-pvc
      - name: temp-storage
        emptyDir:
          sizeLimit: 2Gi
      - name: logs
        emptyDir:
          sizeLimit: 3Gi
      
      nodeSelector:
        kubernetes.io/arch: amd64
        node-type: compute
      
      tolerations:
      - key: "compute-node"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - order-service
              topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: getit-production
  labels:
    app: order-service
    component: core-service
    platform: getit-bangladesh
  annotations:
    description: "Order Service for GetIt Bangladesh"
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - port: 3003
    targetPort: 3003
    protocol: TCP
    name: http
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
  selector:
    app: order-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-service
  namespace: getit-production
  labels:
    app: order-service
    component: core-service
    platform: getit-bangladesh
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: order-documents-pvc
  namespace: getit-production
  labels:
    app: order-service
    component: storage
    platform: getit-bangladesh
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: standard-storage
  resources:
    requests:
      storage: 50Gi
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: order-service-pdb
  namespace: getit-production
  labels:
    app: order-service
    component: core-service
    platform: getit-bangladesh
spec:
  minAvailable: 3
  selector:
    matchLabels:
      app: order-service
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: order-service-network-policy
  namespace: getit-production
  labels:
    app: order-service
    component: security
    platform: getit-bangladesh
spec:
  podSelector:
    matchLabels:
      app: order-service
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: api-gateway
    - podSelector:
        matchLabels:
          app: customer-web
    - podSelector:
        matchLabels:
          app: vendor-dashboard
    - podSelector:
        matchLabels:
          app: admin-panel
    ports:
    - protocol: TCP
      port: 3003
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: postgresql
    ports:
    - protocol: TCP
      port: 5432
  - to:
    - podSelector:
        matchLabels:
          app: mongodb
    ports:
    - protocol: TCP
      port: 27017
  - to:
    - podSelector:
        matchLabels:
          app: redis
    ports:
    - protocol: TCP
      port: 6379
  - to:
    - podSelector:
        matchLabels:
          component: core-service
    ports:
    - protocol: TCP
      port: 3000
    - protocol: TCP
      port: 3001
    - protocol: TCP
      port: 3002
    - protocol: TCP
      port: 3004
    - protocol: TCP
      port: 3005
    - protocol: TCP
      port: 3006
    - protocol: TCP
      port: 3007
    - protocol: TCP
      port: 3009
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80