# Jaeger Configuration for GetIt Bangladesh
# Amazon.com/Shopee.sg-Level Distributed Tracing

# Collector configuration
collector:
  # gRPC server configuration
  grpc-server:
    host-port: 0.0.0.0:14250
  
  # HTTP server configuration
  http-server:
    host-port: 0.0.0.0:14268
  
  # Zipkin compatibility
  zipkin:
    host-port: 0.0.0.0:9411
  
  # Storage configuration
  es:
    server-urls: http://elasticsearch:9200
    username: elastic
    password: changeme
    index-prefix: jaeger
    max-span-age: 72h
    num-shards: 5
    num-replicas: 1
    bulk-size: 5000000
    bulk-workers: 1
    bulk-actions: 1000
    bulk-flush-interval: 200ms
    create-index-templates: true
    version: 7
  
  # Sampling configuration
  sampling:
    strategies-file: /etc/jaeger/sampling_strategies.json

# Query configuration
query:
  # Server configuration
  http-server:
    host-port: 0.0.0.0:16686
  
  # gRPC configuration
  grpc-server:
    host-port: 0.0.0.0:16685
  
  # UI configuration
  ui:
    config: /etc/jaeger/ui-config.json
  
  # Storage configuration
  es:
    server-urls: http://elasticsearch:9200
    username: elastic
    password: changeme
    index-prefix: jaeger
    max-span-age: 72h

# Agent configuration
agent:
  # Server configuration
  processor:
    jaeger-binary:
      server-host-port: 0.0.0.0:14271
      server-max-packet-size: 65000
      server-queue-size: 1000
      workers: 10
    
    jaeger-compact:
      server-host-port: 0.0.0.0:6831
      server-max-packet-size: 65000
      server-queue-size: 1000
      workers: 10
  
  # Reporter configuration
  reporter:
    type: grpc
    grpc:
      host-port: jaeger-collector:14250
      retry:
        max: 3
      discovery:
        min-peers: 3
        conn-check-timeout: 3s

# Ingester configuration
ingester:
  # Kafka configuration
  kafka:
    consumer:
      brokers: ["kafka:9092"]
      topic: jaeger-spans
      group-id: jaeger-ingester
      client-id: jaeger-ingester
      
    producer:
      brokers: ["kafka:9092"]
      topic: jaeger-spans
      batch-size: 100
      batch-timeout: 1s
  
  # Processing configuration
  parallelism: 1000
  deadlock-interval: 0

# Dependencies configuration
dependencies:
  spark:
    master: local[*]
    executor-memory: 1g
    driver-memory: 1g
    executor-cores: 1
    total-executor-cores: 1